name = "remix-live-chat-demo"
main = "src/worker.mjs"
compatibility_date = "2022-04-05"

[[migrations]]
tag = "v1"
new_classes = ["Room"]

[vars]
ORIGIN_URL = "https://8w3tpor496.execute-api.us-west-2.amazonaws.com"

[durable_objects]
bindings = [
  { name = "room", class_name = "Room" },
]

[env.local.vars]
ORIGIN_URL = "http://localhost:3333"

[env.local.durable_objects]
bindings = [
  { name = "room", class_name = "Room" },
]